#!/usr/bin/env python3
"""Remove build artifacts from the BDA ml/ directory (cross-platform).

Usage:
    python clean.py            # remove only intermediates; keep unit*.pdf
    python clean.py --all      # also remove unit*.pdf (full source-only state)
    python clean.py --dry-run  # show what would be removed without removing

Always preserved:
    unit*.Rnw                                  (lecture sources)
    bda_preamble.tex                           (shared LaTeX preamble)
    bda_knitr_setup.R                          (shared knitr setup)
    references.bib                             (bibliography)
    fig/                                       (Boyd-slide PDFs used by Unit 1)
    build.py / clean.py                        (this and its sibling)

Removed by default (intermediates; auto-regenerated by build.py):
    figs/                                      (knitr-generated chunk plots)
    unit*.aux unit*.log unit*.out unit*.tex
    unit*.bbl unit*.blg unit*.toc
    unit*.nav unit*.snm unit*.vrb              (beamer leftovers, if any)
    Sweave.sty                                 (auto-written by knitr)

Removed only with --all:
    unit*.pdf
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).parent.resolve()

INTERMEDIATE_SUFFIXES = {
    ".aux", ".log", ".out", ".tex",
    ".bbl", ".blg", ".toc",
    ".nav", ".snm", ".vrb",
}
PDF_SUFFIX = ".pdf"


def gather(remove_pdf: bool) -> list:
    """Return paths to remove (sorted, deduped)."""
    targets = set()

    for f in ROOT.glob("unit*.*"):
        if f.suffix in INTERMEDIATE_SUFFIXES:
            targets.add(f)
        elif remove_pdf and f.suffix == PDF_SUFFIX:
            targets.add(f)

    figs = ROOT / "figs"
    if figs.is_dir():
        targets.add(figs)

    sweave = ROOT / "Sweave.sty"
    if sweave.exists():
        targets.add(sweave)

    return sorted(targets)


def main(argv: list) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n", 1)[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("\n", 1)[1],
    )
    parser.add_argument(
        "--all", action="store_true",
        help="Also remove unit*.pdf (full clean back to source-only).",
    )
    parser.add_argument(
        "-n", "--dry-run", action="store_true",
        help="Print what would be removed without removing.",
    )
    args = parser.parse_args(argv)

    targets = gather(remove_pdf=args.all)

    if not targets:
        print("Nothing to clean.")
        return 0

    verb = "Would remove" if args.dry_run else "Removing"
    print(f"{verb} {len(targets)} item(s):")
    for t in targets:
        kind = "dir " if t.is_dir() else "file"
        print(f"  [{kind}] {t.relative_to(ROOT)}")

    if args.dry_run:
        return 0

    for t in targets:
        try:
            if t.is_dir():
                shutil.rmtree(t)
            else:
                t.unlink()
        except OSError as e:
            print(f"WARNING: failed to remove {t}: {e}", file=sys.stderr)

    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
